
services:

  front:
    build: ./front

  postgres:
    image: 'postgres:16.2'
    environment:
      POSTGRES_USER: stg
      POSTGRES_PASSWORD: demonstration
      POSTGRES_DB: stg
    volumes:
      - pgdata:/var/lib/postgresql/data

  keydb:
    image: eqalpha/keydb:x86_64_v6.3.4

  back:
    build: ./back

  nginx:
    image: nginx:1.25.4
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:8080'
volumes:
  pgdata:
