
services:

  front:
    build: ./front
    ports:
      # Change the port mapping on your local machine if necessary
      # For further information, see: https://docs.docker.com/compose/compose-file/compose-file-v3/#ports
      - "4173:4173"

  postgres:
    image: 'postgres:16.2'
    environment:
      POSTGRES_USER: stg
      POSTGRES_PASSWORD: demonstration
      POSTGRES_DB: stg
    volumes:
      - pgdata:/var/lib/postgresql/data

  keydb:
    image: eqalpha/keydb:x86_64_v6.3.4

volumes:
  pgdata:
